name: Release CI

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
    - name: build with pyinstaller
      run: |
        python setup.py bdist_app
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          dist/app
